services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web

#    environment:
#      - PORT=8002
#      - DB_URL=postgresql+psycopg://value:pw@db_service:5432/db

    env_file:
      - .env.compose
    ports:
      - 8002:8002
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    depends_on:
      db_service:
        condition: service_healthy
    develop:  
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  
  # postgresql+psycopg://value:pw@hostvalue:5432/db
  db_service:
    image: postgres:15.13
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    expose:
      - "5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U value -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
 
    
   